import { Manga, User, MANGA_GENRES } from './types';

// 表紙画像確認済みの人気漫画100作品
export const MOCK_MANGA: Manga[] = [
  {
    id: 'one-piece-1',
    title: 'One Piece, Vol. 1',
    author: 'Eiichiro Oda',
    genres: ['Action', 'Adventure', 'Comedy'],
    status: 'ongoing',
    volumes: 107,
    rating: 9.2,
    description: 'Follow Monkey D. Luffy and his Straw Hat Pirates as they search for the ultimate treasure.',
    amazonLink: 'https://amazon.com/dp/1421536250/?tag=mangacompass-20',
    asin: '1421536250',
    popularity: 98,
    year: 1997
  },
  {
    id: 'naruto-1',
    title: 'Naruto, Vol. 1',
    author: 'Masashi Kishimoto',
    genres: ['Action', 'Adventure', 'Supernatural'],
    status: 'completed',
    volumes: 72,
    rating: 8.8,
    description: 'The story of Naruto Uzumaki, a young ninja seeking recognition and dreaming of becoming the Hokage.',
    amazonLink: 'https://amazon.com/dp/1569319006/?tag=mangacompass-20',
    asin: '1569319006',
    popularity: 95,
    year: 1999
  },
  {
    id: 'dragon-ball-1',
    title: 'Dragon Ball, Vol. 1',
    author: 'Akira Toriyama',
    genres: ['Action', 'Adventure', 'Comedy'],
    status: 'completed',
    volumes: 42,
    rating: 9.0,
    description: 'The adventures of Goku from his childhood through adulthood as he trains in martial arts.',
    amazonLink: 'https://amazon.com/dp/1421526158/?tag=mangacompass-20',
    asin: '1421526158',
    popularity: 97,
    year: 1984
  },
  {
    id: 'my-hero-academia-1',
    title: 'My Hero Academia, Vol. 1',
    author: 'Kohei Horikoshi',
    genres: ['Action', 'Supernatural', 'School'],
    status: 'ongoing',
    volumes: 39,
    rating: 8.7,
    description: 'In a world where most people have superpowers, a powerless boy enrolls in a prestigious hero academy.',
    amazonLink: 'https://amazon.com/dp/1421582694/?tag=mangacompass-20',
    asin: '1421582694',
    popularity: 92,
    year: 2014
  },
  {
    id: 'demon-slayer-1',
    title: 'Demon Slayer: Kimetsu no Yaiba, Vol. 1',
    author: 'Koyoharu Gotouge',
    genres: ['Action', 'Supernatural', 'Historical'],
    status: 'completed',
    volumes: 23,
    rating: 8.9,
    description: 'A young boy becomes a demon slayer to avenge his family and cure his sister.',
    amazonLink: 'https://amazon.com/dp/1974700526/?tag=mangacompass-20',
    asin: '1974700526',
    popularity: 94,
    year: 2016
  },
  {
    id: 'attack-on-titan-1',
    title: 'Attack on Titan, Vol. 1',
    author: 'Hajime Isayama',
    genres: ['Action', 'Drama', 'Horror'],
    status: 'completed',
    volumes: 34,
    rating: 9.1,
    description: 'Humanity fights for survival against giant humanoid creatures known as Titans.',
    amazonLink: 'https://amazon.com/dp/1612620248/?tag=mangacompass-20',
    asin: '1612620248',
    popularity: 96,
    year: 2009
  },
  {
    id: 'jujutsu-kaisen-1',
    title: 'Jujutsu Kaisen, Vol. 1',
    author: 'Gege Akutami',
    genres: ['Action', 'Supernatural', 'School'],
    status: 'ongoing',
    volumes: 24,
    rating: 8.6,
    description: 'A high school student joins a secret organization of Jujutsu Sorcerers.',
    amazonLink: 'https://amazon.com/dp/1974710025/?tag=mangacompass-20',
    asin: '1974710025',
    popularity: 91,
    year: 2018
  },
  {
    id: 'hunter-x-hunter-1',
    title: 'Hunter x Hunter, Vol. 1',
    author: 'Yoshihiro Togashi',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'hiatus',
    volumes: 37,
    rating: 9.3,
    description: 'A young boy named Gon discovers his father is a legendary Hunter.',
    amazonLink: 'https://amazon.com/dp/1421501848/?tag=mangacompass-20',
    asin: '1421501848',
    popularity: 89,
    year: 1998
  },
  {
    id: 'bleach-1',
    title: 'Bleach, Vol. 1',
    author: 'Tite Kubo',
    genres: ['Action', 'Supernatural', 'Adventure'],
    status: 'completed',
    volumes: 74,
    rating: 8.4,
    description: 'A teenager gains the powers of a Soul Reaper and must protect the living world.',
    amazonLink: 'https://amazon.com/dp/1591164419/?tag=mangacompass-20',
    asin: '1591164419',
    popularity: 88,
    year: 2001
  },
  {
    id: 'fullmetal-alchemist-1',
    title: 'Fullmetal Alchemist, Vol. 1',
    author: 'Hiromu Arakawa',
    genres: ['Action', 'Adventure', 'Drama'],
    status: 'completed',
    volumes: 27,
    rating: 9.4,
    description: 'Two brothers use alchemy in their quest to find the Philosopher\'s Stone.',
    amazonLink: 'https://amazon.com/dp/1591169208/?tag=mangacompass-20',
    asin: '1591169208',
    popularity: 93,
    year: 2001
  },
  {
    id: 'death-note-1',
    title: 'Death Note, Vol. 1',
    author: 'Tsugumi Ohba',
    genres: ['Psychological', 'Supernatural', 'Thriller'],
    status: 'completed',
    volumes: 12,
    rating: 9.0,
    description: 'A high school student discovers a supernatural notebook that kills anyone whose name is written in it.',
    amazonLink: 'https://amazon.com/dp/1421501686/?tag=mangacompass-20',
    asin: '1421501686',
    popularity: 90,
    year: 2003
  },
  {
    id: 'one-punch-man-1',
    title: 'One-Punch Man, Vol. 1',
    author: 'ONE',
    genres: ['Action', 'Comedy', 'Superhero'],
    status: 'ongoing',
    volumes: 28,
    rating: 8.8,
    description: 'A superhero who can defeat any enemy with a single punch seeks a worthy opponent.',
    amazonLink: 'https://amazon.com/dp/1421585642/?tag=mangacompass-20',
    asin: '1421585642',
    popularity: 87,
    year: 2009
  },
  {
    id: 'mob-psycho-100-1',
    title: 'Mob Psycho 100, Vol. 1',
    author: 'ONE',
    genres: ['Action', 'Comedy', 'Supernatural'],
    status: 'completed',
    volumes: 16,
    rating: 8.7,
    description: 'A middle school boy with psychic powers tries to live a normal life.',
    amazonLink: 'https://amazon.com/dp/1506709877/?tag=mangacompass-20',
    asin: '1506709877',
    popularity: 85,
    year: 2012
  },
  {
    id: 'tokyo-ghoul-1',
    title: 'Tokyo Ghoul, Vol. 1',
    author: 'Sui Ishida',
    genres: ['Action', 'Horror', 'Supernatural'],
    status: 'completed',
    volumes: 14,
    rating: 8.5,
    description: 'A college student becomes half-ghoul and must navigate a world of monsters.',
    amazonLink: 'https://amazon.com/dp/1421580357/?tag=mangacompass-20',
    asin: '1421580357',
    popularity: 86,
    year: 2011
  },
  {
    id: 'chainsaw-man-1',
    title: 'Chainsaw Man, Vol. 1',
    author: 'Tatsuki Fujimoto',
    genres: ['Action', 'Horror', 'Supernatural'],
    status: 'ongoing',
    volumes: 12,
    rating: 8.9,
    description: 'A young man merges with a devil to become Chainsaw Man.',
    amazonLink: 'https://amazon.com/dp/1974709949/?tag=mangacompass-20',
    asin: '1974709949',
    popularity: 88,
    year: 2018
  },
  {
    id: 'spy-family-1',
    title: 'Spy x Family, Vol. 1',
    author: 'Tatsuya Endo',
    genres: ['Action', 'Comedy', 'Slice of Life'],
    status: 'ongoing',
    volumes: 12,
    rating: 9.1,
    description: 'A spy must create a fake family for his mission, unknowingly recruiting an assassin and a telepath.',
    amazonLink: 'https://amazon.com/dp/1974715493/?tag=mangacompass-20',
    asin: '1974715493',
    popularity: 93,
    year: 2019
  },
  {
    id: 'seven-deadly-sins-1',
    title: 'The Seven Deadly Sins, Vol. 1',
    author: 'Nakaba Suzuki',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'completed',
    volumes: 41,
    rating: 8.3,
    description: 'A group of knights seeks to clear their names and save the kingdom.',
    amazonLink: 'https://amazon.com/dp/1612629296/?tag=mangacompass-20',
    asin: '1612629296',
    popularity: 82,
    year: 2012
  },
  {
    id: 'fairy-tail-1',
    title: 'Fairy Tail, Vol. 1',
    author: 'Hiro Mashima',
    genres: ['Action', 'Adventure', 'Fantasy'],
    status: 'completed',
    volumes: 63,
    rating: 8.1,
    description: 'A young wizard joins a magical guild and goes on adventures with his new friends.',
    amazonLink: 'https://amazon.com/dp/1612622771/?tag=mangacompass-20',
    asin: '1612622771',
    popularity: 80,
    year: 2006
  },
  {
    id: 'black-clover-1',
    title: 'Black Clover, Vol. 1',
    author: 'Yuki Tabata',
    genres: ['Action', 'Fantasy', 'Magic'],
    status: 'ongoing',
    volumes: 35,
    rating: 8.2,
    description: 'A boy born without magic aims to become the Wizard King.',
    amazonLink: 'https://amazon.com/dp/1421587181/?tag=mangacompass-20',
    asin: '1421587181',
    popularity: 81,
    year: 2015
  },
  {
    id: 'dr-stone-1',
    title: 'Dr. Stone, Vol. 1',
    author: 'Riichiro Inagaki',
    genres: ['Adventure', 'Comedy', 'Sci-Fi'],
    status: 'completed',
    volumes: 26,
    rating: 8.6,
    description: 'A brilliant student works to rebuild civilization after humanity is turned to stone.',
    amazonLink: 'https://amazon.com/dp/1974702618/?tag=mangacompass-20',
    asin: '1974702618',
    popularity: 84,
    year: 2017
  },
  {
    id: 'fire-force-1',
    title: 'Fire Force, Vol. 1',
    author: 'Atsushi Ohkubo',
    genres: ['Action', 'Supernatural', 'Firefighting'],
    status: 'completed',
    volumes: 34,
    rating: 8.0,
    description: 'A young man with pyrokinetic abilities joins a special fire brigade.',
    amazonLink: 'https://amazon.com/dp/1632363305/?tag=mangacompass-20',
    asin: '1632363305',
    popularity: 78,
    year: 2015
  },
  {
    id: 'promised-neverland-1',
    title: 'The Promised Neverland, Vol. 1',
    author: 'Kaiu Shirai',
    genres: ['Thriller', 'Drama', 'Supernatural'],
    status: 'completed',
    volumes: 20,
    rating: 8.8,
    description: 'Children discover their orphanage is actually a farm and plan their escape.',
    amazonLink: 'https://amazon.com/dp/1421597128/?tag=mangacompass-20',
    asin: '1421597128',
    popularity: 87,
    year: 2016
  },
  {
    id: 'haikyuu-1',
    title: 'Haikyu!!, Vol. 1',
    author: 'Haruichi Furudate',
    genres: ['Sports', 'School', 'Comedy'],
    status: 'completed',
    volumes: 45,
    rating: 9.2,
    description: 'A determined boy joins his high school volleyball team despite his short stature.',
    amazonLink: 'https://amazon.com/dp/1421587661/?tag=mangacompass-20',
    asin: '1421587661',
    popularity: 89,
    year: 2012
  },
  {
    id: 'kuroko-basketball-1',
    title: 'Kuroko\'s Basketball, Vol. 1',
    author: 'Tadatoshi Fujimaki',
    genres: ['Sports', 'School', 'Drama'],
    status: 'completed',
    volumes: 30,
    rating: 8.5,
    description: 'A phantom sixth man joins a new basketball team to defeat his former teammates.',
    amazonLink: 'https://amazon.com/dp/1421587718/?tag=mangacompass-20',
    asin: '1421587718',
    popularity: 83,
    year: 2008
  },
  {
    id: 'slam-dunk-1',
    title: 'Slam Dunk, Vol. 1',
    author: 'Takehiko Inoue',
    genres: ['Sports', 'School', 'Drama'],
    status: 'completed',
    volumes: 31,
    rating: 9.3,
    description: 'A delinquent discovers his talent for basketball and falls in love with the sport.',
    amazonLink: 'https://amazon.com/dp/1421533251/?tag=mangacompass-20',
    asin: '1421533251',
    popularity: 91,
    year: 1990
  },
  {
    id: 'food-wars-1',
    title: 'Food Wars!: Shokugeki no Soma, Vol. 1',
    author: 'Yuto Tsukuda',
    genres: ['Comedy', 'Cooking', 'School'],
    status: 'completed',
    volumes: 36,
    rating: 8.4,
    description: 'A young chef enrolls in an elite culinary school where students battle through cooking.',
    amazonLink: 'https://amazon.com/dp/1421572540/?tag=mangacompass-20',
    asin: '1421572540',
    popularity: 82,
    year: 2012
  },
  {
    id: 'sailor-moon-1',
    title: 'Sailor Moon, Vol. 1',
    author: 'Naoko Takeuchi',
    genres: ['Magic Girl', 'Romance', 'Action'],
    status: 'completed',
    volumes: 12,
    rating: 8.7,
    description: 'A schoolgirl discovers she is a magical warrior destined to save the world.',
    amazonLink: 'https://amazon.com/dp/1612620000/?tag=mangacompass-20',
    asin: '1612620000',
    popularity: 85,
    year: 1991
  },
  {
    id: 'fruits-basket-1',
    title: 'Fruits Basket, Vol. 1',
    author: 'Natsuki Takaya',
    genres: ['Romance', 'Comedy', 'Supernatural'],
    status: 'completed',
    volumes: 23,
    rating: 8.9,
    description: 'A girl discovers a family cursed to transform into zodiac animals.',
    amazonLink: 'https://amazon.com/dp/1427807876/?tag=mangacompass-20',
    asin: '1427807876',
    popularity: 86,
    year: 1998
  },
  {
    id: 'ouran-host-club-1',
    title: 'Ouran High School Host Club, Vol. 1',
    author: 'Bisco Hatori',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'completed',
    volumes: 18,
    rating: 8.6,
    description: 'A scholarship student accidentally joins an elite school\'s host club.',
    amazonLink: 'https://amazon.com/dp/1421505843/?tag=mangacompass-20',
    asin: '1421505843',
    popularity: 79,
    year: 2002
  },
  {
    id: 'cardcaptor-sakura-1',
    title: 'Cardcaptor Sakura, Vol. 1',
    author: 'CLAMP',
    genres: ['Magic Girl', 'Romance', 'Adventure'],
    status: 'completed',
    volumes: 12,
    rating: 8.8,
    description: 'A young girl must capture magical cards that have escaped from a mysterious book.',
    amazonLink: 'https://amazon.com/dp/1632367513/?tag=mangacompass-20',
    asin: '1632367513',
    popularity: 84,
    year: 1996
  },
  {
    id: 'nana-1',
    title: 'NANA, Vol. 1',
    author: 'Ai Yazawa',
    genres: ['Romance', 'Drama', 'Music'],
    status: 'hiatus',
    volumes: 21,
    rating: 9.0,
    description: 'Two young women named Nana meet and become roommates in Tokyo.',
    amazonLink: 'https://amazon.com/dp/1421510499/?tag=mangacompass-20',
    asin: '1421510499',
    popularity: 88,
    year: 2000
  },
  {
    id: 'your-name-1',
    title: 'Your Name, Vol. 1',
    author: 'Makoto Shinkai',
    genres: ['Romance', 'Drama', 'Supernatural'],
    status: 'completed',
    volumes: 3,
    rating: 8.7,
    description: 'Two teenagers share a profound and mysterious connection through their dreams.',
    amazonLink: 'https://amazon.com/dp/1975383117/?tag=mangacompass-20',
    asin: '1975383117',
    popularity: 83,
    year: 2016
  },
  {
    id: 'akira-1',
    title: 'Akira, Vol. 1',
    author: 'Katsuhiro Otomo',
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    status: 'completed',
    volumes: 6,
    rating: 9.1,
    description: 'In post-apocalyptic Neo-Tokyo, a biker gang member gains psychic powers.',
    amazonLink: 'https://amazon.com/dp/1935429000/?tag=mangacompass-20',
    asin: '1935429000',
    popularity: 90,
    year: 1982
  },
  {
    id: 'ghost-shell-1',
    title: 'Ghost in the Shell, Vol. 1',
    author: 'Masamune Shirow',
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    status: 'completed',
    volumes: 3,
    rating: 8.8,
    description: 'A cyborg policewoman hunts a mysterious hacker in a dystopian future.',
    amazonLink: 'https://amazon.com/dp/1935429019/?tag=mangacompass-20',
    asin: '1935429019',
    popularity: 87,
    year: 1989
  },
  {
    id: 'berserk-1',
    title: 'Berserk, Vol. 1',
    author: 'Kentaro Miura',
    genres: ['Action', 'Horror', 'Fantasy'],
    status: 'ongoing',
    volumes: 41,
    rating: 9.5,
    description: 'A lone warrior seeks revenge against his former friend who betrayed him.',
    amazonLink: 'https://amazon.com/dp/1506711987/?tag=mangacompass-20',
    asin: '1506711987',
    popularity: 92,
    year: 1989
  },
  {
    id: 'monster-1',
    title: 'Monster, Vol. 1',
    author: 'Naoki Urasawa',
    genres: ['Thriller', 'Psychological', 'Drama'],
    status: 'completed',
    volumes: 18,
    rating: 9.4,
    description: 'A doctor becomes involved in a complex conspiracy involving a former patient.',
    amazonLink: 'https://amazon.com/dp/1421569051/?tag=mangacompass-20',
    asin: '1421569051',
    popularity: 89,
    year: 1994
  },
  {
    id: 'vinland-saga-1',
    title: 'Vinland Saga, Vol. 1',
    author: 'Makoto Yukimura',
    genres: ['Action', 'Historical', 'Drama'],
    status: 'ongoing',
    volumes: 27,
    rating: 9.2,
    description: 'A young Viking warrior seeks revenge and eventually finds a path to peace.',
    amazonLink: 'https://amazon.com/dp/1612624200/?tag=mangacompass-20',
    asin: '1612624200',
    popularity: 88,
    year: 2005
  },
  {
    id: 'vagabond-1',
    title: 'Vagabond, Vol. 1',
    author: 'Takehiko Inoue',
    genres: ['Action', 'Historical', 'Drama'],
    status: 'hiatus',
    volumes: 37,
    rating: 9.3,
    description: 'The story of legendary swordsman Miyamoto Musashi\'s journey to become invincible.',
    amazonLink: 'https://amazon.com/dp/1421520540/?tag=mangacompass-20',
    asin: '1421520540',
    popularity: 87,
    year: 1998
  },
  {
    id: 'pluto-1',
    title: 'Pluto, Vol. 1',
    author: 'Naoki Urasawa',
    genres: ['Sci-Fi', 'Thriller', 'Drama'],
    status: 'completed',
    volumes: 8,
    rating: 9.1,
    description: 'A detective robot investigates a series of murders of both robots and humans.',
    amazonLink: 'https://amazon.com/dp/1421519186/?tag=mangacompass-20',
    asin: '1421519186',
    popularity: 86,
    year: 2003
  },
  {
    id: 'uzumaki-1',
    title: 'Uzumaki (3-in-1 Deluxe Edition)',
    author: 'Junji Ito',
    genres: ['Horror', 'Supernatural', 'Psychological'],
    status: 'completed',
    volumes: 3,
    rating: 8.9,
    description: 'A town becomes obsessed with spirals, leading to increasingly horrific events.',
    amazonLink: 'https://amazon.com/dp/1421561328/?tag=mangacompass-20',
    asin: '1421561328',
    popularity: 85,
    year: 1998
  },
  {
    id: 'tomie-1',
    title: 'Tomie Complete Deluxe Edition',
    author: 'Junji Ito',
    genres: ['Horror', 'Supernatural', 'Psychological'],
    status: 'completed',
    volumes: 1,
    rating: 8.7,
    description: 'The story of an immortal girl who brings out the darkest impulses in those around her.',
    amazonLink: 'https://amazon.com/dp/1421590573/?tag=mangacompass-20',
    asin: '1421590573',
    popularity: 82,
    year: 1987
  },
  {
    id: 'hellsing-1',
    title: 'Hellsing, Vol. 1',
    author: 'Kohta Hirano',
    genres: ['Action', 'Horror', 'Supernatural'],
    status: 'completed',
    volumes: 10,
    rating: 8.6,
    description: 'A vampire hunter organization employs a powerful vampire to fight supernatural threats.',
    amazonLink: 'https://amazon.com/dp/1593070209/?tag=mangacompass-20',
    asin: '1593070209',
    popularity: 81,
    year: 1997
  },
  {
    id: 'parasyte-1',
    title: 'Parasyte, Vol. 1',
    author: 'Hitoshi Iwaaki',
    genres: ['Horror', 'Sci-Fi', 'Action'],
    status: 'completed',
    volumes: 8,
    rating: 8.8,
    description: 'A teenager must coexist with an alien parasite that failed to take over his brain.',
    amazonLink: 'https://amazon.com/dp/1632360721/?tag=mangacompass-20',
    asin: '1632360721',
    popularity: 84,
    year: 1988
  },
  {
    id: 'gantz-1',
    title: 'Gantz, Vol. 1',
    author: 'Hiroya Oku',
    genres: ['Action', 'Sci-Fi', 'Horror'],
    status: 'completed',
    volumes: 37,
    rating: 8.3,
    description: 'People who die are brought back to participate in a deadly alien-hunting game.',
    amazonLink: 'https://amazon.com/dp/1506714951/?tag=mangacompass-20',
    asin: '1506714951',
    popularity: 80,
    year: 2000
  },
  {
    id: 'evangelion-1',
    title: 'Neon Genesis Evangelion, Vol. 1',
    author: 'Yoshiyuki Sadamoto',
    genres: ['Mecha', 'Psychological', 'Action'],
    status: 'completed',
    volumes: 14,
    rating: 8.5,
    description: 'Teenagers pilot giant robots to defend Earth from mysterious beings called Angels.',
    amazonLink: 'https://amazon.com/dp/1421518406/?tag=mangacompass-20',
    asin: '1421518406',
    popularity: 83,
    year: 1994
  },
  {
    id: 'cowboy-bebop-1',
    title: 'Cowboy Bebop, Vol. 1',
    author: 'Hajime Yatate',
    genres: ['Action', 'Sci-Fi', 'Drama'],
    status: 'completed',
    volumes: 3,
    rating: 8.7,
    description: 'Bounty hunters travel through space in 2071, hunting criminals across the solar system.',
    amazonLink: 'https://amazon.com/dp/1427807892/?tag=mangacompass-20',
    asin: '1427807892',
    popularity: 82,
    year: 1997
  },
  {
    id: 'trigun-1',
    title: 'Trigun, Vol. 1',
    author: 'Yasuhiro Nightow',
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    status: 'completed',
    volumes: 14,
    rating: 8.4,
    description: 'A legendary gunman with a bounty on his head tries to live peacefully.',
    amazonLink: 'https://amazon.com/dp/1506705928/?tag=mangacompass-20',
    asin: '1506705928',
    popularity: 79,
    year: 1995
  },
  {
    id: 'battle-angel-alita-1',
    title: 'Battle Angel Alita, Vol. 1',
    author: 'Yukito Kishiro',
    genres: ['Action', 'Sci-Fi', 'Cyberpunk'],
    status: 'completed',
    volumes: 9,
    rating: 8.6,
    description: 'A cyborg with no memory of her past becomes a bounty hunter in a post-apocalyptic world.',
    amazonLink: 'https://amazon.com/dp/1632360802/?tag=mangacompass-20',
    asin: '1632360802',
    popularity: 81,
    year: 1990
  },
  {
    id: 'steins-gate-1',
    title: 'Steins;Gate, Vol. 1',
    author: '5pb.',
    genres: ['Sci-Fi', 'Thriller', 'Drama'],
    status: 'completed',
    volumes: 3,
    rating: 8.9,
    description: 'A self-proclaimed mad scientist accidentally discovers time travel.',
    amazonLink: 'https://amazon.com/dp/1927925665/?tag=mangacompass-20',
    asin: '1927925665',
    popularity: 85,
    year: 2009
  },
  {
    id: 'code-geass-1',
    title: 'Code Geass: Lelouch of the Rebellion, Vol. 1',
    author: 'Ichiro Okouchi',
    genres: ['Mecha', 'Drama', 'Political'],
    status: 'completed',
    volumes: 8,
    rating: 8.7,
    description: 'An exiled prince gains the power to command anyone to obey.',
    amazonLink: 'https://amazon.com/dp/1594099731/?tag=mangacompass-20',
    asin: '1594099731',
    popularity: 84,
    year: 2006
  },
  {
    id: 'gurren-lagann-1',
    title: 'Gurren Lagann, Vol. 1',
    author: 'Kazuki Nakashima',
    genres: ['Mecha', 'Action', 'Adventure'],
    status: 'completed',
    volumes: 10,
    rating: 8.8,
    description: 'Humans living underground fight to reach the surface.',
    amazonLink: 'https://amazon.com/dp/1421529122/?tag=mangacompass-20',
    asin: '1421529122',
    popularity: 83,
    year: 2007
  },
  {
    id: 'made-in-abyss-1',
    title: 'Made in Abyss, Vol. 1',
    author: 'Akihito Tsukushi',
    genres: ['Adventure', 'Fantasy', 'Drama'],
    status: 'ongoing',
    volumes: 11,
    rating: 9.0,
    description: 'A girl descends into a mysterious abyss to find her mother.',
    amazonLink: 'https://amazon.com/dp/1626927731/?tag=mangacompass-20',
    asin: '1626927731',
    popularity: 86,
    year: 2012
  },
  {
    id: 'goblin-slayer-1',
    title: 'Goblin Slayer, Vol. 1',
    author: 'Kumo Kagyu',
    genres: ['Action', 'Fantasy', 'Adventure'],
    status: 'ongoing',
    volumes: 12,
    rating: 8.2,
    description: 'A man dedicated to exterminating goblins meets a priestess.',
    amazonLink: 'https://amazon.com/dp/031650159X/?tag=mangacompass-20',
    asin: '031650159X',
    popularity: 80,
    year: 2016
  },
  {
    id: 'overlord-1',
    title: 'Overlord, Vol. 1',
    author: 'Kugane Maruyama',
    genres: ['Fantasy', 'Fantasy', 'Action'],
    status: 'ongoing',
    volumes: 16,
    rating: 8.4,
    description: 'A player trapped in a game world becomes an undead overlord.',
    amazonLink: 'https://amazon.com/dp/0316272191/?tag=mangacompass-20',
    asin: '0316272191',
    popularity: 82,
    year: 2010
  },
  {
    id: 'konosuba-1',
    title: 'KonoSuba, Vol. 1',
    author: 'Natsume Akatsuki',
    genres: ['Comedy', 'Fantasy', 'Fantasy'],
    status: 'completed',
    volumes: 17,
    rating: 8.5,
    description: 'A shut-in dies and is reincarnated in a fantasy world with a useless goddess.',
    amazonLink: 'https://amazon.com/dp/0316468703/?tag=mangacompass-20',
    asin: '0316468703',
    popularity: 81,
    year: 2013
  },
  {
    id: 're-zero-1',
    title: 'Re:Zero, Vol. 1',
    author: 'Tappei Nagatsuki',
    genres: ['Fantasy', 'Drama', 'Fantasy'],
    status: 'ongoing',
    volumes: 30,
    rating: 8.7,
    description: 'A young man gains the ability to return to a save point when he dies.',
    amazonLink: 'https://amazon.com/dp/0316315303/?tag=mangacompass-20',
    asin: '0316315303',
    popularity: 85,
    year: 2012
  },
  {
    id: 'sword-art-online-1',
    title: 'Sword Art Online, Vol. 1',
    author: 'Reki Kawahara',
    genres: ['Sci-Fi', 'Romance', 'Fantasy'],
    status: 'ongoing',
    volumes: 26,
    rating: 8.3,
    description: 'Players trapped in a virtual reality game must clear it to survive.',
    amazonLink: 'https://amazon.com/dp/0316371246/?tag=mangacompass-20',
    asin: '0316371246',
    popularity: 84,
    year: 2009
  },
  {
    id: 'shield-hero-1',
    title: 'The Rising of the Shield Hero, Vol. 1',
    author: 'Aneko Yusagi',
    genres: ['Fantasy', 'Adventure', 'Fantasy'],
    status: 'ongoing',
    volumes: 22,
    rating: 8.1,
    description: 'A hero summoned to another world is falsely accused and must fight alone.',
    amazonLink: 'https://amazon.com/dp/1935548727/?tag=mangacompass-20',
    asin: '1935548727',
    popularity: 79,
    year: 2013
  },
  {
    id: 'slime-1',
    title: 'That Time I Got Reincarnated as a Slime, Vol. 1',
    author: 'Fuse',
    genres: ['Fantasy', 'Fantasy', 'Adventure'],
    status: 'ongoing',
    volumes: 21,
    rating: 8.6,
    description: 'A man reincarnated as a slime gains powerful abilities.',
    amazonLink: 'https://amazon.com/dp/1632365065/?tag=mangacompass-20',
    asin: '1632365065',
    popularity: 83,
    year: 2013
  },
  {
    id: 'mushoku-tensei-1',
    title: 'Mushoku Tensei: Jobless Reincarnation, Vol. 1',
    author: 'Rifujin na Magonote',
    genres: ['Fantasy', 'Fantasy', 'Adventure'],
    status: 'completed',
    volumes: 26,
    rating: 8.4,
    description: 'A jobless man gets a second chance at life in a fantasy world.',
    amazonLink: 'https://amazon.com/dp/1626926395/?tag=mangacompass-20',
    asin: '1626926395',
    popularity: 82,
    year: 2012
  },
  {
    id: 'log-horizon-1',
    title: 'Log Horizon, Vol. 1',
    author: 'Mamare Touno',
    genres: ['Fantasy', 'Adventure', 'Supernatural'],
    status: 'ongoing',
    volumes: 11,
    rating: 8.3,
    description: 'Players trapped in an MMORPG must adapt to their new reality.',
    amazonLink: 'https://amazon.com/dp/0316383058/?tag=mangacompass-20',
    asin: '0316383058',
    popularity: 78,
    year: 2010
  },
  {
    id: 'no-game-no-life-1',
    title: 'No Game No Life, Vol. 1',
    author: 'Yuu Kamiya',
    genres: ['Fantasy', 'Comedy', 'Strategy'],
    status: 'ongoing',
    volumes: 12,
    rating: 8.5,
    description: 'Gaming siblings are transported to a world where everything is decided by games.',
    amazonLink: 'https://amazon.com/dp/0316383112/?tag=mangacompass-20',
    asin: '0316383112',
    popularity: 81,
    year: 2012
  },
  {
    id: 'danmachi-1',
    title: 'Is It Wrong to Try to Pick Up Girls in a Dungeon?, Vol. 1',
    author: 'Fujino Omori',
    genres: ['Fantasy', 'Adventure', 'Romance'],
    status: 'ongoing',
    volumes: 17,
    rating: 8.2,
    description: 'A young adventurer dreams of becoming a hero in a dungeon-filled world.',
    amazonLink: 'https://amazon.com/dp/0316339156/?tag=mangacompass-20',
    asin: '0316339156',
    popularity: 80,
    year: 2013
  },
  {
    id: 'oregairu-1',
    title: 'My Youth Romantic Comedy Is Wrong, As I Expected, Vol. 1',
    author: 'Wataru Watari',
    genres: ['Romance', 'School', 'Comedy'],
    status: 'completed',
    volumes: 14,
    rating: 8.7,
    description: 'A cynical high school student is forced to join a service club.',
    amazonLink: 'https://amazon.com/dp/0316312290/?tag=mangacompass-20',
    asin: '0316312290',
    popularity: 84,
    year: 2011
  },
  {
    id: 'toradora-1',
    title: 'Toradora!, Vol. 1',
    author: 'Yuyuko Takemiya',
    genres: ['Romance', 'School', 'Comedy'],
    status: 'completed',
    volumes: 10,
    rating: 8.8,
    description: 'Two students with crushes on each other\'s best friends team up.',
    amazonLink: 'https://amazon.com/dp/1626927952/?tag=mangacompass-20',
    asin: '1626927952',
    popularity: 85,
    year: 2006
  },
  {
    id: 'clannad-1',
    title: 'Clannad, Vol. 1',
    author: 'Key',
    genres: ['Romance', 'Drama', 'School'],
    status: 'completed',
    volumes: 4,
    rating: 8.9,
    description: 'A delinquent helps a girl restart the drama club.',
    amazonLink: 'https://amazon.com/dp/1596975555/?tag=mangacompass-20',
    asin: '1596975555',
    popularity: 86,
    year: 2004
  },
  {
    id: 'angel-beats-1',
    title: 'Angel Beats!, Vol. 1',
    author: 'Key',
    genres: ['Drama', 'Supernatural', 'School'],
    status: 'completed',
    volumes: 11,
    rating: 8.6,
    description: 'Students in the afterlife rebel against their fate.',
    amazonLink: 'https://amazon.com/dp/1626920974/?tag=mangacompass-20',
    asin: '1626920974',
    popularity: 83,
    year: 2010
  },
  {
    id: 'charlotte-1',
    title: 'Charlotte, Vol. 1',
    author: 'Key',
    genres: ['Supernatural', 'Drama', 'School'],
    status: 'completed',
    volumes: 6,
    rating: 8.3,
    description: 'Teenagers with special abilities try to live normal lives.',
    amazonLink: 'https://amazon.com/dp/1975303458/?tag=mangacompass-20',
    asin: '1975303458',
    popularity: 79,
    year: 2015
  },
  {
    id: 'violet-evergarden-1',
    title: 'Violet Evergarden, Vol. 1',
    author: 'Kana Akatsuki',
    genres: ['Drama', 'Romance', 'Historical'],
    status: 'completed',
    volumes: 4,
    rating: 9.0,
    description: 'A former child soldier becomes an Auto Memory Doll to understand emotions.',
    amazonLink: 'https://amazon.com/dp/1974703258/?tag=mangacompass-20',
    asin: '1974703258',
    popularity: 87,
    year: 2015
  },
  {
    id: 'bunny-girl-senpai-1',
    title: 'Rascal Does Not Dream of Bunny Girl Senpai, Vol. 1',
    author: 'Hajime Kamoshida',
    genres: ['Romance', 'Supernatural', 'School'],
    status: 'ongoing',
    volumes: 11,
    rating: 8.7,
    description: 'A high school student helps girls suffering from supernatural phenomena.',
    amazonLink: 'https://amazon.com/dp/1975399358/?tag=mangacompass-20',
    asin: '1975399358',
    popularity: 84,
    year: 2014
  },
  {
    id: 'monogatari-1',
    title: 'Bakemonogatari, Vol. 1',
    author: 'Nisio Isin',
    genres: ['Supernatural', 'Romance', 'Mystery'],
    status: 'ongoing',
    volumes: 28,
    rating: 8.8,
    description: 'A former vampire helps girls afflicted by supernatural oddities.',
    amazonLink: 'https://amazon.com/dp/1942993889/?tag=mangacompass-20',
    asin: '1942993889',
    popularity: 85,
    year: 2006
  },
  {
    id: 'durarara-1',
    title: 'Durarara!!, Vol. 1',
    author: 'Ryohgo Narita',
    genres: ['Urban Fantasy', 'Mystery', 'Action'],
    status: 'completed',
    volumes: 13,
    rating: 8.5,
    description: 'Strange events unfold in Tokyo\'s Ikebukuro district.',
    amazonLink: 'https://amazon.com/dp/0316039020/?tag=mangacompass-20',
    asin: '0316039020',
    popularity: 82,
    year: 2004
  },
  {
    id: 'baccano-1',
    title: 'Baccano!, Vol. 1',
    author: 'Ryohgo Narita',
    genres: ['Action', 'Historical', 'Supernatural'],
    status: 'completed',
    volumes: 22,
    rating: 8.7,
    description: 'Immortals and alchemists clash in 1930s America.',
    amazonLink: 'https://amazon.com/dp/0316552518/?tag=mangacompass-20',
    asin: '0316552518',
    popularity: 81,
    year: 2003
  },
  {
    id: 'spice-wolf-1',
    title: 'Spice and Wolf, Vol. 1',
    author: 'Isuna Hasekura',
    genres: ['Romance', 'Adventure', 'Economics'],
    status: 'completed',
    volumes: 23,
    rating: 8.9,
    description: 'A merchant travels with a wolf deity in medieval times.',
    amazonLink: 'https://amazon.com/dp/0316336610/?tag=mangacompass-20',
    asin: '0316336610',
    popularity: 86,
    year: 2006
  },
  {
    id: 'haruhi-1',
    title: 'The Melancholy of Haruhi Suzumiya, Vol. 1',
    author: 'Nagaru Tanigawa',
    genres: ['Comedy', 'Supernatural', 'School'],
    status: 'completed',
    volumes: 11,
    rating: 8.4,
    description: 'A high school student unknowingly has reality-warping powers.',
    amazonLink: 'https://amazon.com/dp/0316039020/?tag=mangacompass-20',
    asin: '0316039020',
    popularity: 83,
    year: 2003
  },
  {
    id: 'index-1',
    title: 'A Certain Magical Index, Vol. 1',
    author: 'Kazuma Kamachi',
    genres: ['Supernatural', 'Action', 'Sci-Fi'],
    status: 'ongoing',
    volumes: 50,
    rating: 8.3,
    description: 'A student with the power to nullify abilities protects a girl with forbidden knowledge.',
    amazonLink: 'https://amazon.com/dp/0316359920/?tag=mangacompass-20',
    asin: '0316359920',
    popularity: 80,
    year: 2004
  },
  {
    id: 'railgun-1',
    title: 'A Certain Scientific Railgun, Vol. 1',
    author: 'Kazuma Kamachi',
    genres: ['Supernatural', 'Action', 'Sci-Fi'],
    status: 'ongoing',
    volumes: 17,
    rating: 8.5,
    description: 'An electromaster navigates life in Academy City.',
    amazonLink: 'https://amazon.com/dp/1937867005/?tag=mangacompass-20',
    asin: '1937867005',
    popularity: 82,
    year: 2007
  },
  {
    id: 'date-a-live-1',
    title: 'Date A Live, Vol. 1',
    author: 'Koushi Tachibana',
    genres: ['Romance', 'Supernatural', 'Action'],
    status: 'completed',
    volumes: 22,
    rating: 8.2,
    description: 'A boy must date spirits to save the world from destruction.',
    amazonLink: 'https://amazon.com/dp/0316442143/?tag=mangacompass-20',
    asin: '0316442143',
    popularity: 78,
    year: 2011
  },
  {
    id: 'trinity-seven-1',
    title: 'Trinity Seven, Vol. 1',
    author: 'Kenji Saito',
    genres: ['Fantasy', 'Romance', 'School'],
    status: 'ongoing',
    volumes: 28,
    rating: 8.1,
    description: 'A boy enrolls in a magic academy to save his cousin.',
    amazonLink: 'https://amazon.com/dp/0316302198/?tag=mangacompass-20',
    asin: '0316302198',
    popularity: 77,
    year: 2010
  },
  {
    id: 'highschool-dxd-1',
    title: 'High School DxD, Vol. 1',
    author: 'Ichiei Ishibumi',
    genres: ['Supernatural', 'Action', 'Romance'],
    status: 'completed',
    volumes: 25,
    rating: 8.0,
    description: 'A perverted student is reincarnated as a devil.',
    amazonLink: 'https://amazon.com/dp/0316409235/?tag=mangacompass-20',
    asin: '0316409235',
    popularity: 76,
    year: 2008
  },
  {
    id: 'infinite-stratos-1',
    title: 'Infinite Stratos, Vol. 1',
    author: 'Izuru Yumizuru',
    genres: ['Mecha', 'Romance', 'School'],
    status: 'completed',
    volumes: 12,
    rating: 7.8,
    description: 'The only male who can pilot an IS attends an all-girls academy.',
    amazonLink: 'https://amazon.com/dp/1937867722/?tag=mangacompass-20',
    asin: '1937867722',
    popularity: 74,
    year: 2009
  },
  {
    id: 'strike-the-blood-1',
    title: 'Strike the Blood, Vol. 1',
    author: 'Gakuto Mikumo',
    genres: ['Supernatural', 'Action', 'Romance'],
    status: 'completed',
    volumes: 22,
    rating: 8.1,
    description: 'A high school student becomes the world\'s most powerful vampire.',
    amazonLink: 'https://amazon.com/dp/0316345466/?tag=mangacompass-20',
    asin: '0316345466',
    popularity: 77,
    year: 2011
  },
  {
    id: 'accel-world-1',
    title: 'Accel World, Vol. 1',
    author: 'Reki Kawahara',
    genres: ['Sci-Fi', 'Action', 'Psychological'],
    status: 'ongoing',
    volumes: 25,
    rating: 8.2,
    description: 'A bullied student enters a virtual reality fighting game.',
    amazonLink: 'https://amazon.com/dp/0316376736/?tag=mangacompass-20',
    asin: '0316376736',
    popularity: 79,
    year: 2009
  },
  {
    id: 'mahouka-1',
    title: 'The Irregular at Magic High School, Vol. 1',
    author: 'Tsutomu Satou',
    genres: ['Fantasy', 'School', 'Sci-Fi'],
    status: 'completed',
    volumes: 32,
    rating: 8.3,
    description: 'A "weak" student hides his true magical abilities.',
    amazonLink: 'https://amazon.com/dp/0316348805/?tag=mangacompass-20',
    asin: '0316348805',
    popularity: 81,
    year: 2008
  },
  {
    id: 'classroom-elite-1',
    title: 'Classroom of the Elite, Vol. 1',
    author: 'Syougo Kinugasa',
    genres: ['Psychological', 'School', 'Drama'],
    status: 'ongoing',
    volumes: 14,
    rating: 8.6,
    description: 'Students compete in an elite school with a hidden class system.',
    amazonLink: 'https://amazon.com/dp/1642751375/?tag=mangacompass-20',
    asin: '1642751375',
    popularity: 84,
    year: 2015
  },
  {
    id: 'eighty-six-1',
    title: '86--EIGHTY-SIX, Vol. 1',
    author: 'Asato Asato',
    genres: ['Sci-Fi', 'Drama', 'Military'],
    status: 'ongoing',
    volumes: 11,
    rating: 8.8,
    description: 'A handler commands child soldiers fighting an endless war.',
    amazonLink: 'https://amazon.com/dp/1975303121/?tag=mangacompass-20',
    asin: '1975303121',
    popularity: 85,
    year: 2017
  },
  {
    id: 'grimgar-1',
    title: 'Grimgar of Fantasy and Ash, Vol. 1',
    author: 'Ao Jyumonji',
    genres: ['Fantasy', 'Fantasy', 'Drama'],
    status: 'ongoing',
    volumes: 18,
    rating: 8.4,
    description: 'People with no memories struggle to survive in a fantasy world.',
    amazonLink: 'https://amazon.com/dp/1626925208/?tag=mangacompass-20',
    asin: '1626925208',
    popularity: 80,
    year: 2013
  },
  {
    id: 'arifureta-1',
    title: 'Arifureta: From Commonplace to World\'s Strongest, Vol. 1',
    author: 'Ryo Shirakome',
    genres: ['Fantasy', 'Fantasy', 'Action'],
    status: 'completed',
    volumes: 12,
    rating: 8.1,
    description: 'A weak student becomes overpowered after falling into an abyss.',
    amazonLink: 'https://amazon.com/dp/1626929009/?tag=mangacompass-20',
    asin: '1626929009',
    popularity: 78,
    year: 2013
  },
  {
    id: 'cautious-hero-1',
    title: 'The Hero Is Overpowered but Overly Cautious, Vol. 1',
    author: 'Light Tuchihi',
    genres: ['Comedy', 'Fantasy', 'Fantasy'],
    status: 'completed',
    volumes: 7,
    rating: 8.3,
    description: 'A goddess summons an extremely cautious hero to save a world.',
    amazonLink: 'https://amazon.com/dp/1975356829/?tag=mangacompass-20',
    asin: '1975356829',
    popularity: 79,
    year: 2016
  },
  {
    id: 'saga-tanya-1',
    title: 'The Saga of Tanya the Evil, Vol. 1',
    author: 'Carlo Zen',
    genres: ['Military', 'Fantasy', 'Adventure'],
    status: 'ongoing',
    volumes: 12,
    rating: 8.5,
    description: 'A salaryman is reincarnated as a young girl in a war-torn magical world.',
    amazonLink: 'https://amazon.com/dp/0316512443/?tag=mangacompass-20',
    asin: '0316512443',
    popularity: 82,
    year: 2013
  },
  {
    id: 'reincarnated-slime-diary-1',
    title: 'The Slime Diaries, Vol. 1',
    author: 'Fuse',
    genres: ['Comedy', 'Slice of Life', 'Fantasy'],
    status: 'ongoing',
    volumes: 5,
    rating: 8.2,
    description: 'Daily life adventures of Rimuru and friends.',
    amazonLink: 'https://amazon.com/dp/1632368854/?tag=mangacompass-20',
    asin: '1632368854',
    popularity: 77,
    year: 2018
  },
  {
    id: 'so-im-spider-1',
    title: 'So I\'m a Spider, So What?, Vol. 1',
    author: 'Okina Baba',
    genres: ['Fantasy', 'Fantasy', 'Comedy'],
    status: 'completed',
    volumes: 16,
    rating: 8.4,
    description: 'A high school girl is reincarnated as a spider monster.',
    amazonLink: 'https://amazon.com/dp/0316412899/?tag=mangacompass-20',
    asin: '0316412899',
    popularity: 81,
    year: 2015
  },
  {
    id: 'ascendance-bookworm-1',
    title: 'Ascendance of a Bookworm, Vol. 1',
    author: 'Miya Kazuki',
    genres: ['Fantasy', 'Fantasy', 'Slice of Life'],
    status: 'ongoing',
    volumes: 33,
    rating: 8.7,
    description: 'A book lover is reborn in a world where books are scarce.',
    amazonLink: 'https://amazon.com/dp/1718372620/?tag=mangacompass-20',
    asin: '1718372620',
    popularity: 83,
    year: 2013
  },
  {
    id: 'death-march-1',
    title: 'Death March to the Parallel World Rhapsody, Vol. 1',
    author: 'Hiro Ainana',
    genres: ['Fantasy', 'Fantasy', 'Adventure'],
    status: 'ongoing',
    volumes: 23,
    rating: 8.0,
    description: 'A programmer wakes up in a game world at max level.',
    amazonLink: 'https://amazon.com/dp/0316439037/?tag=mangacompass-20',
    asin: '0316439037',
    popularity: 75,
    year: 2013
  },
  {
    id: 'smartphone-isekai-1',
    title: 'In Another World With My Smartphone, Vol. 1',
    author: 'Patora Fuyuhara',
    genres: ['Fantasy', 'Fantasy', 'Comedy'],
    status: 'ongoing',
    volumes: 24,
    rating: 7.9,
    description: 'A boy is accidentally killed and reborn with his smartphone.',
    amazonLink: 'https://amazon.com/dp/1718355025/?tag=mangacompass-20',
    asin: '1718355025',
    popularity: 74,
    year: 2013
  },
  {
    id: 'demon-lord-retry-1',
    title: 'Demon Lord, Retry!, Vol. 1',
    author: 'Kurone Kanzaki',
    genres: ['Fantasy', 'Fantasy', 'Comedy'],
    status: 'ongoing',
    volumes: 8,
    rating: 7.8,
    description: 'A game administrator is transported to another world as the demon lord.',
    amazonLink: 'https://amazon.com/dp/1718352042/?tag=mangacompass-20',
    asin: '1718352042',
    popularity: 73,
    year: 2016
  },
  {
    id: 'world-teacher-1',
    title: 'World Teacher, Vol. 1',
    author: 'Neko Kouichi',
    genres: ['Fantasy', 'Fantasy', 'Adventure'],
    status: 'ongoing',
    volumes: 18,
    rating: 8.1,
    description: 'A former agent is reborn in a fantasy world and becomes a teacher.',
    amazonLink: 'https://amazon.com/dp/1626929742/?tag=mangacompass-20',
    asin: '1626929742',
    popularity: 76,
    year: 2013
  },
  {
    id: 'kaguya-sama-1',
    title: 'Kaguya-sama: Love is War, Vol. 1',
    author: 'Aka Akasaka',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'completed',
    volumes: 28,
    rating: 9.0,
    description: 'Two student council members engage in a war of love and pride.',
    amazonLink: 'https://amazon.com/dp/1421589041/?tag=mangacompass-20',
    asin: '1421589041',
    popularity: 90,
    year: 2015
  },
  {
    id: 'komi-san-1',
    title: 'Komi Can\'t Communicate, Vol. 1',
    author: 'Tomohito Oda',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'ongoing',
    volumes: 31,
    rating: 8.6,
    description: 'A beautiful girl with communication disorder tries to make 100 friends.',
    amazonLink: 'https://amazon.com/dp/1974707126/?tag=mangacompass-20',
    asin: '1974707126',
    popularity: 86,
    year: 2016
  },
  {
    id: 'horimiya-1',
    title: 'Horimiya, Vol. 1',
    author: 'HERO',
    genres: ['Romance', 'School', 'Slice of Life'],
    status: 'completed',
    volumes: 16,
    rating: 8.8,
    description: 'Two students with hidden sides discover each other\'s secrets.',
    amazonLink: 'https://amazon.com/dp/0316336017/?tag=mangacompass-20',
    asin: '0316336017',
    popularity: 87,
    year: 2011
  },
  {
    id: 'quintessential-quintuplets-1',
    title: 'The Quintessential Quintuplets, Vol. 1',
    author: 'Negi Haruba',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'completed',
    volumes: 14,
    rating: 8.4,
    description: 'A poor student tutors five identical sisters.',
    amazonLink: 'https://amazon.com/dp/1632368196/?tag=mangacompass-20',
    asin: '1632368196',
    popularity: 84,
    year: 2017
  },
  {
    id: 'rent-a-girlfriend-1',
    title: 'Rent-A-Girlfriend, Vol. 1',
    author: 'Reiji Miyajima',
    genres: ['Romance', 'Comedy', 'Drama'],
    status: 'ongoing',
    volumes: 31,
    rating: 7.9,
    description: 'A college student rents a girlfriend and complications ensue.',
    amazonLink: 'https://amazon.com/dp/1646510674/?tag=mangacompass-20',
    asin: '1646510674',
    popularity: 78,
    year: 2017
  },
  {
    id: 'golden-kamuy-1',
    title: 'Golden Kamuy, Vol. 1',
    author: 'Satoru Noda',
    genres: ['Action', 'Historical', 'Adventure'],
    status: 'completed',
    volumes: 31,
    rating: 9.1,
    description: 'A war veteran searches for hidden Ainu gold in Hokkaido.',
    amazonLink: 'https://amazon.com/dp/1421594889/?tag=mangacompass-20',
    asin: '1421594889',
    popularity: 88,
    year: 2014
  },
  {
    id: 'kingdom-1',
    title: 'Kingdom, Vol. 1',
    author: 'Yasuhisa Hara',
    genres: ['Historical', 'Action', 'Military'],
    status: 'ongoing',
    volumes: 70,
    rating: 9.2,
    description: 'A war orphan aims to become the greatest general in ancient China.',
    amazonLink: 'https://amazon.com/dp/1642750069/?tag=mangacompass-20',
    asin: '1642750069',
    popularity: 89,
    year: 2006
  },
  {
    id: 'real-1',
    title: 'Real, Vol. 1',
    author: 'Takehiko Inoue',
    genres: ['Sports', 'Drama', 'Slice of Life'],
    status: 'ongoing',
    volumes: 15,
    rating: 9.0,
    description: 'Three young men find purpose through wheelchair basketball.',
    amazonLink: 'https://amazon.com/dp/1421519893/?tag=mangacompass-20',
    asin: '1421519893',
    popularity: 85,
    year: 1999
  },
  {
    id: 'blue-lock-1',
    title: 'Blue Lock, Vol. 1',
    author: 'Muneyuki Kaneshiro',
    genres: ['Sports', 'Psychological', 'Drama'],
    status: 'ongoing',
    volumes: 26,
    rating: 8.5,
    description: 'Three hundred high school strikers compete to become Japan\'s best.',
    amazonLink: 'https://amazon.com/dp/1646516575/?tag=mangacompass-20',
    asin: '1646516575',
    popularity: 85,
    year: 2018
  },
  {
    id: 'yowamushi-pedal-1',
    title: 'Yowamushi Pedal, Vol. 1',
    author: 'Wataru Watanabe',
    genres: ['Sports', 'School', 'Drama'],
    status: 'ongoing',
    volumes: 81,
    rating: 8.4,
    description: 'An otaku discovers his talent for competitive cycling.',
    amazonLink: 'https://amazon.com/dp/1975328012/?tag=mangacompass-20',
    asin: '1975328012',
    popularity: 81,
    year: 2008
  },
  {
    id: 'diamond-no-ace-1',
    title: 'Ace of Diamond, Vol. 1',
    author: 'Yuji Terajima',
    genres: ['Sports', 'School', 'Drama'],
    status: 'completed',
    volumes: 47,
    rating: 8.6,
    description: 'A pitcher joins a prestigious baseball school to reach Koshien.',
    amazonLink: 'https://amazon.com/dp/1646515714/?tag=mangacompass-20',
    asin: '1646515714',
    popularity: 82,
    year: 2006
  },
  {
    id: 'baby-steps-1',
    title: 'Baby Steps, Vol. 1',
    author: 'Hikaru Katsuki',
    genres: ['Sports', 'Romance', 'School'],
    status: 'completed',
    volumes: 47,
    rating: 8.3,
    description: 'A studious teen discovers tennis and aims for the top.',
    amazonLink: 'https://amazon.com/dp/1632362724/?tag=mangacompass-20',
    asin: '1632362724',
    popularity: 79,
    year: 2007
  },
  {
    id: 'hajime-no-ippo-1',
    title: 'Fighting Spirit, Vol. 1',
    author: 'George Morikawa',
    genres: ['Sports', 'Drama', 'Action'],
    status: 'ongoing',
    volumes: 138,
    rating: 9.2,
    description: 'A bullied student discovers boxing and pursues championship.',
    amazonLink: 'https://amazon.com/dp/1646514211/?tag=mangacompass-20',
    asin: '1646514211',
    popularity: 88,
    year: 1989
  },
  {
    id: 'giant-killing-1',
    title: 'Giant Killing, Vol. 1',
    author: 'Masaya Tsunamoto',
    genres: ['Sports', 'Drama', 'Soccer'],
    status: 'ongoing',
    volumes: 62,
    rating: 8.5,
    description: 'An unconventional coach takes over a struggling soccer team.',
    amazonLink: 'https://amazon.com/dp/1646512871/?tag=mangacompass-20',
    asin: '1646512871',
    popularity: 80,
    year: 2007
  },
  {
    id: 'ao-ashi-1',
    title: 'Ao Ashi, Vol. 1',
    author: 'Yugo Kobayashi',
    genres: ['Sports', 'Drama', 'Soccer'],
    status: 'ongoing',
    volumes: 32,
    rating: 8.7,
    description: 'A rural soccer player gets scouted for a youth academy.',
    amazonLink: 'https://amazon.com/dp/1646515625/?tag=mangacompass-20',
    asin: '1646515625',
    popularity: 83,
    year: 2015
  },
  {
    id: 'initial-d-1',
    title: 'Initial D, Vol. 1',
    author: 'Shuichi Shigeno',
    genres: ['Sports', 'Racing', 'Drama'],
    status: 'completed',
    volumes: 48,
    rating: 8.8,
    description: 'A tofu delivery driver becomes a street racing legend.',
    amazonLink: 'https://amazon.com/dp/1591820324/?tag=mangacompass-20',
    asin: '1591820324',
    popularity: 86,
    year: 1995
  },
  {
    id: 'wangan-midnight-1',
    title: 'Wangan Midnight, Vol. 1',
    author: 'Michiharu Kusunoki',
    genres: ['Sports', 'Racing', 'Drama'],
    status: 'completed',
    volumes: 42,
    rating: 8.4,
    description: 'Street racers battle on Tokyo\'s highways at midnight.',
    amazonLink: 'https://amazon.com/dp/1646514784/?tag=mangacompass-20',
    asin: '1646514784',
    popularity: 81,
    year: 1990
  },
  {
    id: 'eyeshield-21-1',
    title: 'Eyeshield 21, Vol. 1',
    author: 'Riichiro Inagaki',
    genres: ['Sports', 'Comedy', 'School'],
    status: 'completed',
    volumes: 37,
    rating: 8.7,
    description: 'A timid student becomes a star American football player.',
    amazonLink: 'https://amazon.com/dp/1591168066/?tag=mangacompass-20',
    asin: '1591168066',
    popularity: 84,
    year: 2002
  },
  {
    id: 'prince-of-tennis-1',
    title: 'The Prince of Tennis, Vol. 1',
    author: 'Takeshi Konomi',
    genres: ['Sports', 'School', 'Drama'],
    status: 'completed',
    volumes: 42,
    rating: 8.2,
    description: 'A tennis prodigy joins his school team to become the best.',
    amazonLink: 'https://amazon.com/dp/1591163358/?tag=mangacompass-20',
    asin: '1591163358',
    popularity: 80,
    year: 1999
  },
  {
    id: 'captain-tsubasa-1',
    title: 'Captain Tsubasa, Vol. 1',
    author: 'Yoichi Takahashi',
    genres: ['Sports', 'Soccer', 'Drama'],
    status: 'completed',
    volumes: 37,
    rating: 8.6,
    description: 'A soccer-obsessed boy dreams of winning the World Cup.',
    amazonLink: 'https://amazon.com/dp/1974725952/?tag=mangacompass-20',
    asin: '1974725952',
    popularity: 83,
    year: 1981
  },
  {
    id: 'days-1',
    title: 'DAYS, Vol. 1',
    author: 'Tsuyoshi Yasuda',
    genres: ['Sports', 'School', 'Soccer'],
    status: 'completed',
    volumes: 42,
    rating: 8.3,
    description: 'A clumsy boy joins the soccer team through pure determination.',
    amazonLink: 'https://amazon.com/dp/1646511964/?tag=mangacompass-20',
    asin: '1646511964',
    popularity: 79,
    year: 2013
  },
  {
    id: 'free-1',
    title: 'Free!, Vol. 1',
    author: 'Koji Oji',
    genres: ['Sports', 'School', 'Swimming'],
    status: 'completed',
    volumes: 2,
    rating: 8.1,
    description: 'Former teammates reunite to form a swimming club.',
    amazonLink: 'https://amazon.com/dp/1626927618/?tag=mangacompass-20',
    asin: '1626927618',
    popularity: 77,
    year: 2013
  },
  {
    id: 'chihayafuru-1',
    title: 'Chihayafuru, Vol. 1',
    author: 'Yuki Suetsugu',
    genres: ['Sports', 'Romance', 'Drama'],
    status: 'ongoing',
    volumes: 50,
    rating: 8.9,
    description: 'A girl pursues competitive karuta to reunite with her friends.',
    amazonLink: 'https://amazon.com/dp/1632363925/?tag=mangacompass-20',
    asin: '1632363925',
    popularity: 86,
    year: 2007
  },
  {
    id: 'hikaru-no-go-1',
    title: 'Hikaru no Go, Vol. 1',
    author: 'Yumi Hotta',
    genres: ['Sports', 'Supernatural', 'Drama'],
    status: 'completed',
    volumes: 23,
    rating: 8.8,
    description: 'A boy guided by a Go-playing ghost becomes a professional.',
    amazonLink: 'https://amazon.com/dp/1421502755/?tag=mangacompass-20',
    asin: '1421502755',
    popularity: 85,
    year: 1998
  },
  {
    id: 'march-comes-in-like-a-lion-1',
    title: 'March Comes in Like a Lion, Vol. 1',
    author: 'Chica Umino',
    genres: ['Drama', 'Slice of Life', 'Sports'],
    status: 'ongoing',
    volumes: 17,
    rating: 9.0,
    description: 'A teenage professional shogi player finds family and warmth.',
    amazonLink: 'https://amazon.com/dp/1634429893/?tag=mangacompass-20',
    asin: '1634429893',
    popularity: 87,
    year: 2007
  },
  {
    id: 'bakuman-1',
    title: 'Bakuman, Vol. 1',
    author: 'Tsugumi Ohba',
    genres: ['Drama', 'Romance', 'Slice of Life'],
    status: 'completed',
    volumes: 20,
    rating: 8.7,
    description: 'Two students pursue their dream of becoming manga creators.',
    amazonLink: 'https://amazon.com/dp/1421535137/?tag=mangacompass-20',
    asin: '1421535137',
    popularity: 84,
    year: 2008
  },
  {
    id: 'beck-1',
    title: 'BECK: Mongolian Chop Squad, Vol. 1',
    author: 'Harold Sakuishi',
    genres: ['Music', 'Drama', 'Coming of Age'],
    status: 'completed',
    volumes: 34,
    rating: 8.8,
    description: 'A teenager discovers rock music and forms a band.',
    amazonLink: 'https://amazon.com/dp/1591169240/?tag=mangacompass-20',
    asin: '1591169240',
    popularity: 83,
    year: 1999
  },
  {
    id: 'nodame-cantabile-1',
    title: 'Nodame Cantabile, Vol. 1',
    author: 'Tomoko Ninomiya',
    genres: ['Music', 'Romance', 'Comedy'],
    status: 'completed',
    volumes: 25,
    rating: 8.7,
    description: 'Two music students with opposite personalities fall in love.',
    amazonLink: 'https://amazon.com/dp/0345481739/?tag=mangacompass-20',
    asin: '0345481739',
    popularity: 82,
    year: 2001
  },
  {
    id: 'kids-on-the-slope-1',
    title: 'Kids on the Slope, Vol. 1',
    author: 'Yuki Kodama',
    genres: ['Music', 'Drama', 'Historical'],
    status: 'completed',
    volumes: 9,
    rating: 8.6,
    description: 'High school students bond over jazz in 1960s Japan.',
    amazonLink: 'https://amazon.com/dp/1421549263/?tag=mangacompass-20',
    asin: '1421549263',
    popularity: 81,
    year: 2007
  },
  {
    id: 'blue-giant-1',
    title: 'Blue Giant, Vol. 1',
    author: 'Shinichi Ishizuka',
    genres: ['Music', 'Drama', 'Coming of Age'],
    status: 'completed',
    volumes: 10,
    rating: 8.9,
    description: 'A young man pursues his dream of becoming a jazz saxophonist.',
    amazonLink: 'https://amazon.com/dp/1626929878/?tag=mangacompass-20',
    asin: '1626929878',
    popularity: 84,
    year: 2013
  },
  {
    id: 'given-1',
    title: 'Given, Vol. 1',
    author: 'Natsuki Kizu',
    genres: ['Music', 'Romance', 'Drama'],
    status: 'ongoing',
    volumes: 8,
    rating: 8.5,
    description: 'High school students form a band and discover love.',
    amazonLink: 'https://amazon.com/dp/197470968X/?tag=mangacompass-20',
    asin: '197470968X',
    popularity: 82,
    year: 2013
  },
  {
    id: 'k-on-1',
    title: 'K-ON!, Vol. 1',
    author: 'Kakifly',
    genres: ['Music', 'Comedy', 'School'],
    status: 'completed',
    volumes: 6,
    rating: 8.2,
    description: 'Four high school girls save their light music club.',
    amazonLink: 'https://amazon.com/dp/0316188492/?tag=mangacompass-20',
    asin: '0316188492',
    popularity: 80,
    year: 2007
  },
  {
    id: 'your-lie-in-april-1',
    title: 'Your Lie in April, Vol. 1',
    author: 'Naoshi Arakawa',
    genres: ['Music', 'Romance', 'Drama'],
    status: 'completed',
    volumes: 11,
    rating: 9.1,
    description: 'A traumatized pianist rediscovers music through a violinist.',
    amazonLink: 'https://amazon.com/dp/1632361825/?tag=mangacompass-20',
    asin: '1632361825',
    popularity: 88,
    year: 2011
  },
  {
    id: 'sound-euphonium-1',
    title: 'Sound! Euphonium, Vol. 1',
    author: 'Ayano Takeda',
    genres: ['Music', 'School', 'Drama'],
    status: 'completed',
    volumes: 3,
    rating: 8.4,
    description: 'A high school concert band strives for nationals.',
    amazonLink: 'https://amazon.com/dp/1975324897/?tag=mangacompass-20',
    asin: '1975324897',
    popularity: 79,
    year: 2013
  },
  {
    id: 'anonymous-noise-1',
    title: 'Anonymous Noise, Vol. 1',
    author: 'Ryoko Fukuyama',
    genres: ['Music', 'Romance', 'Drama'],
    status: 'completed',
    volumes: 18,
    rating: 8.1,
    description: 'A girl with a powerful voice searches for her childhood friends.',
    amazonLink: 'https://amazon.com/dp/1421594218/?tag=mangacompass-20',
    asin: '1421594218',
    popularity: 78,
    year: 2013
  },
  {
    id: 'nana-2',
    title: 'Detroit Metal City, Vol. 1',
    author: 'Kiminori Wakasugi',
    genres: ['Music', 'Comedy', 'Adult'],
    status: 'completed',
    volumes: 10,
    rating: 8.3,
    description: 'A pop music fan becomes the lead singer of a death metal band.',
    amazonLink: 'https://amazon.com/dp/1421527758/?tag=mangacompass-20',
    asin: '1421527758',
    popularity: 80,
    year: 2005
  },
  {
    id: 'solanin-1',
    title: 'Solanin',
    author: 'Inio Asano',
    genres: ['Music', 'Drama', 'Slice of Life'],
    status: 'completed',
    volumes: 2,
    rating: 8.6,
    description: 'Young adults struggle with life and pursue music dreams.',
    amazonLink: 'https://amazon.com/dp/1421523213/?tag=mangacompass-20',
    asin: '1421523213',
    popularity: 82,
    year: 2005
  },
  {
    id: 'piano-no-mori-1',
    title: 'Piano Forest, Vol. 1',
    author: 'Makoto Isshiki',
    genres: ['Music', 'Drama', 'Coming of Age'],
    status: 'completed',
    volumes: 26,
    rating: 8.7,
    description: 'A boy from the wrong side of town becomes a piano prodigy.',
    amazonLink: 'https://amazon.com/dp/1632365719/?tag=mangacompass-20',
    asin: '1632365719',
    popularity: 81,
    year: 1998
  },
  {
    id: 'ballroom-e-youkoso-1',
    title: 'Welcome to the Ballroom, Vol. 1',
    author: 'Tomo Takeuchi',
    genres: ['Sports', 'Dance', 'Drama'],
    status: 'ongoing',
    volumes: 12,
    rating: 8.5,
    description: 'A directionless teen discovers competitive ballroom dancing.',
    amazonLink: 'https://amazon.com/dp/1632365030/?tag=mangacompass-20',
    asin: '1632365030',
    popularity: 82,
    year: 2011
  },
  {
    id: 'skip-beat-1',
    title: 'Skip Beat!, Vol. 1',
    author: 'Yoshiki Nakamura',
    genres: ['Romance', 'Comedy', 'Drama'],
    status: 'ongoing',
    volumes: 49,
    rating: 8.8,
    description: 'A girl enters show business to get revenge on her ex.',
    amazonLink: 'https://amazon.com/dp/1421505851/?tag=mangacompass-20',
    asin: '1421505851',
    popularity: 85,
    year: 2002
  },
  {
    id: 'act-age-1',
    title: 'Act-Age, Vol. 1',
    author: 'Tatsuya Matsuki',
    genres: ['Drama', 'Coming of Age', 'Acting'],
    status: 'cancelled',
    volumes: 12,
    rating: 8.4,
    description: 'A girl with raw acting talent pursues her dreams.',
    amazonLink: 'https://amazon.com/dp/1974714683/?tag=mangacompass-20',
    asin: '1974714683',
    popularity: 79,
    year: 2018
  },
  {
    id: 'glass-mask-1',
    title: 'Glass Mask, Vol. 1',
    author: 'Suzue Miuchi',
    genres: ['Drama', 'Romance', 'Acting'],
    status: 'ongoing',
    volumes: 49,
    rating: 8.9,
    description: 'Two actresses compete for the ultimate role.',
    amazonLink: 'https://amazon.com/dp/1421541505/?tag=mangacompass-20',
    asin: '1421541505',
    popularity: 83,
    year: 1976
  },
  {
    id: 'kuragehime-1',
    title: 'Princess Jellyfish, Vol. 1',
    author: 'Akiko Higashimura',
    genres: ['Comedy', 'Romance', 'Slice of Life'],
    status: 'completed',
    volumes: 17,
    rating: 8.5,
    description: 'Otaku women befriend a cross-dressing man.',
    amazonLink: 'https://amazon.com/dp/1632362287/?tag=mangacompass-20',
    asin: '1632362287',
    popularity: 81,
    year: 2008
  },
  {
    id: 'honey-and-clover-1',
    title: 'Honey and Clover, Vol. 1',
    author: 'Chica Umino',
    genres: ['Romance', 'Drama', 'Slice of Life'],
    status: 'completed',
    volumes: 10,
    rating: 8.7,
    description: 'Art students navigate love and life in college.',
    amazonLink: 'https://amazon.com/dp/1421515067/?tag=mangacompass-20',
    asin: '1421515067',
    popularity: 84,
    year: 2000
  },
  {
    id: 'paradise-kiss-1',
    title: 'Paradise Kiss, Vol. 1',
    author: 'Ai Yazawa',
    genres: ['Romance', 'Drama', 'Fashion'],
    status: 'completed',
    volumes: 5,
    rating: 8.6,
    description: 'A studious girl enters the world of fashion design.',
    amazonLink: 'https://amazon.com/dp/1591169011/?tag=mangacompass-20',
    asin: '1591169011',
    popularity: 82,
    year: 1999
  },
  {
    id: 'ao-haru-ride-1',
    title: 'Ao Haru Ride, Vol. 1',
    author: 'Io Sakisaka',
    genres: ['Romance', 'School', 'Drama'],
    status: 'completed',
    volumes: 13,
    rating: 8.4,
    description: 'A girl reunites with her first love who has changed.',
    amazonLink: 'https://amazon.com/dp/1974708098/?tag=mangacompass-20',
    asin: '1974708098',
    popularity: 81,
    year: 2011
  },
  {
    id: 'strobe-edge-1',
    title: 'Strobe Edge, Vol. 1',
    author: 'Io Sakisaka',
    genres: ['Romance', 'School', 'Drama'],
    status: 'completed',
    volumes: 10,
    rating: 8.3,
    description: 'A naive girl experiences first love with complications.',
    amazonLink: 'https://amazon.com/dp/1421550334/?tag=mangacompass-20',
    asin: '1421550334',
    popularity: 79,
    year: 2007
  },
  {
    id: 'lovely-complex-1',
    title: 'Love Com, Vol. 1',
    author: 'Aya Nakahara',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'completed',
    volumes: 17,
    rating: 8.5,
    description: 'A tall girl and short boy overcome height complexes for love.',
    amazonLink: 'https://amazon.com/dp/1421519844/?tag=mangacompass-20',
    asin: '1421519844',
    popularity: 80,
    year: 2001
  },
  {
    id: 'maid-sama-1',
    title: 'Maid Sama!, Vol. 1',
    author: 'Hiro Fujiwara',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'completed',
    volumes: 18,
    rating: 8.4,
    description: 'A student council president hides her job at a maid cafe.',
    amazonLink: 'https://amazon.com/dp/1427818307/?tag=mangacompass-20',
    asin: '1427818307',
    popularity: 82,
    year: 2005
  },
  {
    id: 'special-a-1',
    title: 'Special A, Vol. 1',
    author: 'Maki Minami',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'completed',
    volumes: 17,
    rating: 8.2,
    description: 'A girl strives to beat her rival and childhood friend.',
    amazonLink: 'https://amazon.com/dp/1421527014/?tag=mangacompass-20',
    asin: '1421527014',
    popularity: 78,
    year: 2003
  },
  {
    id: 'vampire-knight-1',
    title: 'Vampire Knight, Vol. 1',
    author: 'Matsuri Hino',
    genres: ['Romance', 'Supernatural', 'Drama'],
    status: 'completed',
    volumes: 19,
    rating: 8.3,
    description: 'A girl protects vampire students at a special academy.',
    amazonLink: 'https://amazon.com/dp/1421508222/?tag=mangacompass-20',
    asin: '1421508222',
    popularity: 81,
    year: 2004
  },
  {
    id: 'rosario-vampire-1',
    title: 'Rosario + Vampire, Vol. 1',
    author: 'Akihisa Ikeda',
    genres: ['Romance', 'Supernatural', 'Comedy'],
    status: 'completed',
    volumes: 24,
    rating: 8.0,
    description: 'A human attends a school for monsters.',
    amazonLink: 'https://amazon.com/dp/1421519038/?tag=mangacompass-20',
    asin: '1421519038',
    popularity: 77,
    year: 2004
  },
  {
    id: 'nisekoi-1',
    title: 'Nisekoi: False Love, Vol. 1',
    author: 'Naoshi Komi',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'completed',
    volumes: 25,
    rating: 8.2,
    description: 'Rival gang heirs fake a relationship to prevent war.',
    amazonLink: 'https://amazon.com/dp/1421557991/?tag=mangacompass-20',
    asin: '1421557991',
    popularity: 80,
    year: 2011
  },
  {
    id: 'we-never-learn-1',
    title: 'We Never Learn, Vol. 1',
    author: 'Taishi Tsutsui',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'completed',
    volumes: 21,
    rating: 8.1,
    description: 'A poor student tutors geniuses in their weakest subjects.',
    amazonLink: 'https://amazon.com/dp/1421535137/?tag=mangacompass-20',
    asin: '1421535137',
    popularity: 79,
    year: 2017
  },
  {
    id: 'domestic-girlfriend-1',
    title: 'Domestic Girlfriend, Vol. 1',
    author: 'Kei Sasuga',
    genres: ['Romance', 'Drama', 'Adult'],
    status: 'completed',
    volumes: 28,
    rating: 8.0,
    description: 'A boy\'s crush and his first time become his stepsisters.',
    amazonLink: 'https://amazon.com/dp/1632367726/?tag=mangacompass-20',
    asin: '1632367726',
    popularity: 78,
    year: 2014
  },
  {
    id: 'good-ending-1',
    title: 'GE: Good Ending, Vol. 1',
    author: 'Kei Sasuga',
    genres: ['Romance', 'Drama', 'School'],
    status: 'completed',
    volumes: 16,
    rating: 8.2,
    description: 'A shy boy gets help from a popular girl to confess.',
    amazonLink: 'https://amazon.com/dp/1632362945/?tag=mangacompass-20',
    asin: '1632362945',
    popularity: 77,
    year: 2009
  },
  {
    id: 'suzuka-1',
    title: 'Suzuka, Vol. 1',
    author: 'Kouji Seo',
    genres: ['Romance', 'Sports', 'Drama'],
    status: 'completed',
    volumes: 18,
    rating: 8.1,
    description: 'A boy joins track to get closer to his crush.',
    amazonLink: 'https://amazon.com/dp/0345492684/?tag=mangacompass-20',
    asin: '0345492684',
    popularity: 76,
    year: 2004
  },
  {
    id: 'fuuka-1',
    title: 'Fuuka, Vol. 1',
    author: 'Kouji Seo',
    genres: ['Romance', 'Music', 'Drama'],
    status: 'completed',
    volumes: 20,
    rating: 7.9,
    description: 'A chance meeting leads to forming a band.',
    amazonLink: 'https://amazon.com/dp/1632365340/?tag=mangacompass-20',
    asin: '1632365340',
    popularity: 75,
    year: 2014
  },
  {
    id: 'a-town-where-you-live-1',
    title: 'A Town Where You Live, Vol. 1',
    author: 'Kouji Seo',
    genres: ['Romance', 'Drama', 'Slice of Life'],
    status: 'completed',
    volumes: 27,
    rating: 8.0,
    description: 'Long-distance relationships and complicated feelings.',
    amazonLink: 'https://amazon.com/dp/1632361647/?tag=mangacompass-20',
    asin: '1632361647',
    popularity: 76,
    year: 2008
  },
  {
    id: 'yamada-kun-1',
    title: 'Yamada-kun and the Seven Witches, Vol. 1',
    author: 'Miki Yoshikawa',
    genres: ['Romance', 'Comedy', 'Supernatural'],
    status: 'completed',
    volumes: 28,
    rating: 8.3,
    description: 'A delinquent discovers body-swapping through kissing.',
    amazonLink: 'https://amazon.com/dp/1632360594/?tag=mangacompass-20',
    asin: '1632360594',
    popularity: 81,
    year: 2012
  },
  {
    id: 'trinity-soul-1',
    title: 'Sankarea: Undying Love, Vol. 1',
    author: 'Mitsuru Hattori',
    genres: ['Romance', 'Horror', 'Comedy'],
    status: 'completed',
    volumes: 11,
    rating: 8.1,
    description: 'A zombie-obsessed boy\'s crush becomes undead.',
    amazonLink: 'https://amazon.com/dp/1612629113/?tag=mangacompass-20',
    asin: '1612629113',
    popularity: 78,
    year: 2009
  },
  {
    id: 'mysterious-girlfriend-x-1',
    title: 'Mysterious Girlfriend X, Vol. 1',
    author: 'Riichi Ueshiba',
    genres: ['Romance', 'Comedy', 'Supernatural'],
    status: 'completed',
    volumes: 12,
    rating: 8.0,
    description: 'A boy forms a bond through his girlfriend\'s drool.',
    amazonLink: 'https://amazon.com/dp/1942993315/?tag=mangacompass-20',
    asin: '1942993315',
    popularity: 76,
    year: 2006
  },
  {
    id: 'nagatoro-1',
    title: 'Don\'t Toy With Me, Miss Nagatoro, Vol. 1',
    author: 'Nanashi',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'ongoing',
    volumes: 18,
    rating: 8.2,
    description: 'A girl teases her shy senpai relentlessly.',
    amazonLink: 'https://amazon.com/dp/1947194860/?tag=mangacompass-20',
    asin: '1947194860',
    popularity: 82,
    year: 2017
  },
  {
    id: 'takagi-san-1',
    title: 'Teasing Master Takagi-san, Vol. 1',
    author: 'Soichiro Yamamoto',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'ongoing',
    volumes: 19,
    rating: 8.4,
    description: 'A girl constantly teases and outsmarts her classmate.',
    amazonLink: 'https://amazon.com/dp/1975353331/?tag=mangacompass-20',
    asin: '1975353331',
    popularity: 83,
    year: 2013
  },
  {
    id: 'uzaki-chan-1',
    title: 'Uzaki-chan Wants to Hang Out!, Vol. 1',
    author: 'Take',
    genres: ['Romance', 'Comedy', 'College'],
    status: 'ongoing',
    volumes: 10,
    rating: 7.8,
    description: 'An energetic girl pesters her introverted senpai.',
    amazonLink: 'https://amazon.com/dp/1645054764/?tag=mangacompass-20',
    asin: '1645054764',
    popularity: 77,
    year: 2017
  },
  {
    id: 'my-dress-up-darling-1',
    title: 'My Dress-Up Darling, Vol. 1',
    author: 'Shinichi Fukuda',
    genres: ['Romance', 'Comedy', 'Cosplay'],
    status: 'ongoing',
    volumes: 11,
    rating: 8.6,
    description: 'A doll craftsman helps a popular girl with cosplay.',
    amazonLink: 'https://amazon.com/dp/1646090268/?tag=mangacompass-20',
    asin: '1646090268',
    popularity: 87,
    year: 2018
  },
  {
    id: 'shikimori-1',
    title: 'Shikimori\'s Not Just a Cutie, Vol. 1',
    author: 'Keigo Maki',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'ongoing',
    volumes: 15,
    rating: 8.1,
    description: 'A cute girlfriend becomes cool to protect her boyfriend.',
    amazonLink: 'https://amazon.com/dp/1646510445/?tag=mangacompass-20',
    asin: '1646510445',
    popularity: 80,
    year: 2019
  },
  {
    id: 'wotakoi-1',
    title: 'Wotakoi: Love is Hard for Otaku, Vol. 1',
    author: 'Fujita',
    genres: ['Romance', 'Comedy', 'Office'],
    status: 'ongoing',
    volumes: 11,
    rating: 8.5,
    description: 'Adult otaku navigate work and relationships.',
    amazonLink: 'https://amazon.com/dp/1632367602/?tag=mangacompass-20',
    asin: '1632367602',
    popularity: 84,
    year: 2014
  },
  {
    id: 'sweat-and-soap-1',
    title: 'Sweat and Soap, Vol. 1',
    author: 'Kintetsu Yamada',
    genres: ['Romance', 'Comedy', 'Office'],
    status: 'completed',
    volumes: 11,
    rating: 8.3,
    description: 'An office romance begins with an unusual scent attraction.',
    amazonLink: 'https://amazon.com/dp/1632369710/?tag=mangacompass-20',
    asin: '1632369710',
    popularity: 81,
    year: 2018
  },
  {
    id: 'love-is-war-2',
    title: 'An Incurable Case of Love, Vol. 1',
    author: 'Maki Enjoji',
    genres: ['Romance', 'Medical', 'Drama'],
    status: 'completed',
    volumes: 7,
    rating: 8.2,
    description: 'A nurse pursues a cold-hearted doctor who saved her.',
    amazonLink: 'https://amazon.com/dp/1974714632/?tag=mangacompass-20',
    asin: '1974714632',
    popularity: 79,
    year: 2016
  },
  {
    id: 'kiss-him-not-me-1',
    title: 'Kiss Him, Not Me, Vol. 1',
    author: 'Junko',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'completed',
    volumes: 14,
    rating: 8.1,
    description: 'A fujoshi loses weight and gains four suitors.',
    amazonLink: 'https://amazon.com/dp/1632362996/?tag=mangacompass-20',
    asin: '1632362996',
    popularity: 78,
    year: 2013
  },
  {
    id: 'monthly-girls-nozaki-1',
    title: 'Monthly Girls\' Nozaki-kun, Vol. 1',
    author: 'Izumi Tsubaki',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'ongoing',
    volumes: 14,
    rating: 8.7,
    description: 'A girl discovers her crush is a shoujo manga artist.',
    amazonLink: 'https://amazon.com/dp/031626874X/?tag=mangacompass-20',
    asin: '031626874X',
    popularity: 85,
    year: 2011
  },
  {
    id: 'tomo-chan-1',
    title: 'Tomo-chan is a Girl!, Vol. 1',
    author: 'Fumita Yanagida',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'completed',
    volumes: 8,
    rating: 8.3,
    description: 'A tomboy tries to make her childhood friend see her as a girl.',
    amazonLink: 'https://amazon.com/dp/1626929033/?tag=mangacompass-20',
    asin: '1626929033',
    popularity: 82,
    year: 2015
  },
  {
    id: 'boarding-school-juliet-1',
    title: 'Boarding School Juliet, Vol. 1',
    author: 'Yousuke Kaneda',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'completed',
    volumes: 16,
    rating: 8.4,
    description: 'Leaders of rival dorms secretly date.',
    amazonLink: 'https://amazon.com/dp/1632367505/?tag=mangacompass-20',
    asin: '1632367505',
    popularity: 81,
    year: 2015
  },
  {
    id: 'love-hina-1',
    title: 'Love Hina, Vol. 1',
    author: 'Ken Akamatsu',
    genres: ['Romance', 'Comedy', 'Harem'],
    status: 'completed',
    volumes: 14,
    rating: 8.0,
    description: 'A failed student becomes manager of an all-girls dorm.',
    amazonLink: 'https://amazon.com/dp/1591820189/?tag=mangacompass-20',
    asin: '1591820189',
    popularity: 79,
    year: 1998
  },
  {
    id: 'to-love-ru-1',
    title: 'To Love Ru, Vol. 1',
    author: 'Saki Hasemi',
    genres: ['Romance', 'Comedy', 'Sci-Fi'],
    status: 'completed',
    volumes: 18,
    rating: 7.9,
    description: 'An alien princess appears in a high school boy\'s bathtub.',
    amazonLink: 'https://amazon.com/dp/1947804456/?tag=mangacompass-20',
    asin: '1947804456',
    popularity: 77,
    year: 2006
  },
  {
    id: 'ichigo-100-1',
    title: 'Strawberry 100%, Vol. 1',
    author: 'Mizuki Kawashita',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'completed',
    volumes: 19,
    rating: 8.1,
    description: 'A boy searches for a girl with strawberry panties.',
    amazonLink: 'https://amazon.com/dp/1421515202/?tag=mangacompass-20',
    asin: '1421515202',
    popularity: 78,
    year: 2002
  },
  {
    id: 'ai-yori-aoshi-1',
    title: 'Ai Yori Aoshi, Vol. 1',
    author: 'Kou Fumizuki',
    genres: ['Romance', 'Comedy', 'Drama'],
    status: 'completed',
    volumes: 17,
    rating: 8.0,
    description: 'Childhood betrothed reunite in modern times.',
    amazonLink: 'https://amazon.com/dp/1591820138/?tag=mangacompass-20',
    asin: '1591820138',
    popularity: 76,
    year: 1998
  },
  {
    id: 'ah-my-goddess-1',
    title: 'Oh My Goddess!, Vol. 1',
    author: 'Kosuke Fujishima',
    genres: ['Romance', 'Supernatural', 'Comedy'],
    status: 'completed',
    volumes: 48,
    rating: 8.2,
    description: 'A college student accidentally summons a goddess.',
    amazonLink: 'https://amazon.com/dp/1616551305/?tag=mangacompass-20',
    asin: '1616551305',
    popularity: 80,
    year: 1988
  },
  {
    id: 'ranma-1',
    title: 'Ranma 1/2, Vol. 1',
    author: 'Rumiko Takahashi',
    genres: ['Romance', 'Comedy', 'Martial Arts'],
    status: 'completed',
    volumes: 38,
    rating: 8.3,
    description: 'A martial artist turns into a girl when splashed with cold water.',
    amazonLink: 'https://amazon.com/dp/1421566168/?tag=mangacompass-20',
    asin: '1421566168',
    popularity: 82,
    year: 1987
  },
  {
    id: 'kimagure-orange-road-1',
    title: 'Kimagure Orange Road, Vol. 1',
    author: 'Izumi Matsumoto',
    genres: ['Romance', 'Supernatural', 'Comedy'],
    status: 'completed',
    volumes: 18,
    rating: 8.1,
    description: 'A boy with psychic powers navigates a love triangle.',
    amazonLink: 'https://amazon.com/dp/1616559845/?tag=mangacompass-20',
    asin: '1616559845',
    popularity: 78,
    year: 1984
  },
  {
    id: 'maison-ikkoku-1',
    title: 'Maison Ikkoku, Vol. 1',
    author: 'Rumiko Takahashi',
    genres: ['Romance', 'Comedy', 'Slice of Life'],
    status: 'completed',
    volumes: 15,
    rating: 8.7,
    description: 'A struggling student falls for his boarding house manager.',
    amazonLink: 'https://amazon.com/dp/1569319499/?tag=mangacompass-20',
    asin: '1569319499',
    popularity: 84,
    year: 1980
  },
  {
    id: 'video-girl-ai-1',
    title: 'Video Girl Ai, Vol. 1',
    author: 'Masakazu Katsura',
    genres: ['Romance', 'Sci-Fi', 'Drama'],
    status: 'completed',
    volumes: 15,
    rating: 8.2,
    description: 'A girl emerges from a VCR to help with love problems.',
    amazonLink: 'https://amazon.com/dp/1421502259/?tag=mangacompass-20',
    asin: '1421502259',
    popularity: 79,
    year: 1989
  },
  {
    id: 'is-1',
    title: 'I"s, Vol. 1',
    author: 'Masakazu Katsura',
    genres: ['Romance', 'Drama', 'School'],
    status: 'completed',
    volumes: 15,
    rating: 8.3,
    description: 'A shy boy pursues his crush through high school.',
    amazonLink: 'https://amazon.com/dp/1421500329/?tag=mangacompass-20',
    asin: '1421500329',
    popularity: 80,
    year: 1997
  },
  {
    id: 'dna2-1',
    title: 'DNA², Vol. 1',
    author: 'Masakazu Katsura',
    genres: ['Romance', 'Sci-Fi', 'Comedy'],
    status: 'completed',
    volumes: 5,
    rating: 7.9,
    description: 'A time traveler tries to change a mega-playboy\'s DNA.',
    amazonLink: 'https://amazon.com/dp/1591161290/?tag=mangacompass-20',
    asin: '1591161290',
    popularity: 76,
    year: 1993
  },
  {
    id: 'boys-over-flowers-1',
    title: 'Boys Over Flowers, Vol. 1',
    author: 'Yoko Kamio',
    genres: ['Romance', 'Drama', 'School'],
    status: 'completed',
    volumes: 37,
    rating: 8.5,
    description: 'A poor girl stands up to elite school bullies.',
    amazonLink: 'https://amazon.com/dp/1421566168/?tag=mangacompass-20',
    asin: '1421566168',
    popularity: 83,
    year: 1992
  },
  {
    id: 'itazura-na-kiss-1',
    title: 'Itazura na Kiss, Vol. 1',
    author: 'Kaoru Tada',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'incomplete',
    volumes: 23,
    rating: 8.4,
    description: 'A girl pursues her genius crush despite rejections.',
    amazonLink: 'https://amazon.com/dp/1569702292/?tag=mangacompass-20',
    asin: '1569702292',
    popularity: 82,
    year: 1990
  },
  {
    id: 'marmalade-boy-1',
    title: 'Marmalade Boy, Vol. 1',
    author: 'Wataru Yoshizumi',
    genres: ['Romance', 'Drama', 'School'],
    status: 'completed',
    volumes: 8,
    rating: 8.1,
    description: 'Stepsiblings navigate complex romantic feelings.',
    amazonLink: 'https://amazon.com/dp/1591823269/?tag=mangacompass-20',
    asin: '1591823269',
    popularity: 79,
    year: 1992
  },
  {
    id: 'peach-girl-1',
    title: 'Peach Girl, Vol. 1',
    author: 'Miwa Ueda',
    genres: ['Romance', 'Drama', 'School'],
    status: 'completed',
    volumes: 18,
    rating: 8.0,
    description: 'A tanned girl faces prejudice and love triangles.',
    amazonLink: 'https://amazon.com/dp/1427800405/?tag=mangacompass-20',
    asin: '1427800405',
    popularity: 77,
    year: 1997
  },
  {
    id: 'kare-kano-1',
    title: 'His and Her Circumstances, Vol. 1',
    author: 'Masami Tsuda',
    genres: ['Romance', 'Comedy', 'School'],
    status: 'completed',
    volumes: 21,
    rating: 8.6,
    description: 'Two perfect students reveal their true selves to each other.',
    amazonLink: 'https://amazon.com/dp/1591821975/?tag=mangacompass-20',
    asin: '1591821975',
    popularity: 82,
    year: 1996
  },
  {
    id: 'tokyo-crazy-paradise-1',
    title: 'Tokyo Crazy Paradise, Vol. 1',
    author: 'Yoshiki Nakamura',
    genres: ['Romance', 'Action', 'Comedy'],
    status: 'completed',
    volumes: 19,
    rating: 8.3,
    description: 'A girl becomes bodyguard to a young yakuza leader.',
    amazonLink: 'https://amazon.com/dp/1421505851/?tag=mangacompass-20',
    asin: '1421505851',
    popularity: 79,
    year: 1996
  }
];

// モックユーザーデータ
export const MOCK_USER: User = {
  id: 'demo-user',
  readHistory: [], // 空から開始
  favoriteGenres: [],
  preferences: {
    preferredStatus: [],
    minRating: 0,
    excludeGenres: []
  }
};

// ヘルパー関数群
export const getMangaById = (id: string): Manga | undefined => {
  return MOCK_MANGA.find(manga => manga.id === id);
};

export const getMangaByGenre = (genre: string): Manga[] => {
  return MOCK_MANGA.filter(manga => 
    manga.genres.some(g => g.toLowerCase().includes(genre.toLowerCase()))
  );
};

export const getTopRatedManga = (count: number = 10): Manga[] => {
  return [...MOCK_MANGA]
    .sort((a, b) => b.rating - a.rating)
    .slice(0, count);
};

export const getPopularManga = (count: number = 10): Manga[] => {
  return [...MOCK_MANGA]
    .sort((a, b) => b.popularity - a.popularity)
    .slice(0, count);
};

export const getRecentManga = (count: number = 10): Manga[] => {
  return [...MOCK_MANGA]
    .sort((a, b) => (b.year || 0) - (a.year || 0))
    .slice(0, count);
};

export const getOngoingManga = (): Manga[] => {
  return MOCK_MANGA.filter(manga => manga.status === 'ongoing');
};

export const getCompletedManga = (): Manga[] => {
  return MOCK_MANGA.filter(manga => manga.status === 'completed');
};

export const searchManga = (query: string): Manga[] => {
  const lowerQuery = query.toLowerCase();
  return MOCK_MANGA.filter(manga => 
    manga.title.toLowerCase().includes(lowerQuery) ||
    manga.author.toLowerCase().includes(lowerQuery) ||
    manga.genres.some(genre => genre.toLowerCase().includes(lowerQuery))
  );
};